---
- name: Cria Novo Dominio
  hosts: win
  vars:
    temp_address: ${ip_instancia}
    dc_address: ${ip_instancia}
    dc_netmask_cidr: 24
    dc_gateway: ${ip_instancia}
    dc_hostname: 'adfs-lab'
    domain_name: "bwg.lab"
    local_admin: '.\administrator'
    temp_password: 'P@ssw0rd'
    dc_password: 'P@ssw0rd'
    recovery_password: 'P@ssw0rd'
    upstream_dns_1: 8.8.8.8
    upstream_dns_2: 8.8.4.4
    reverse_dns_zone: "172.16.108.0/24"
    ntp_servers: "0.us.pool.ntp.org,1.us.pool.ntp.org,2.us.pool.ntp.org,3.us.pool.ntp.org"
  gather_facts: no
  
  tasks:
  - name: Define IP Estatico
    win_shell: "(new-netipaddress -InterfaceAlias Ethernet0 -IPAddress {{ dc_address }} -prefixlength {{dc_netmask_cidr}} -defaultgateway {{ dc_gateway }})"
    delegate_to: '{{ temp_address }}'  
    ignore_errors: True 

  - name: Define Senha do Admin do Dominio
    win_user:
      name: administrator
      password: "{{dc_password}}"
      state: present
    delegate_to: '{{ dc_address }}'
    ignore_errors: True  
 
  - name: Aguarda o WinRM ficar disponivel
    wait_for_connection:
      timeout: 900
    delegate_to: '{{ dc_address }}'

  - name: Define upstream DNS server 
    win_dns_client:
      adapter_names: '*'
      ipv4_addresses:
      - '{{ upstream_dns_1 }}'
      - '{{ upstream_dns_2 }}'
    delegate_to: '{{ dc_address }}'

  - name: Para servico de horario
    win_service:
      name: w32time
      state: stopped
    delegate_to: '{{ dc_address }}'

  - name: Define NTP Servers
    win_shell: 'w32tm /config /syncfromflags:manual /manualpeerlist:"{{ntp_servers}}"'
    delegate_to: '{{ dc_address }}'

  - name: Inicia serviço de horario
    win_service:
      name: w32time
      state: started  
    delegate_to: '{{ dc_address }}'

  - name: Desabilita Firewall
    win_firewall:
      state: disabled
      profiles:
      - Domain
      - Private
      - Public
    tags: disable_firewall
    delegate_to: '{{ dc_address }}'

  - name: Troca o Hostname
    win_hostname:
      name: '{{ dc_hostname }}'
    register: res
    delegate_to: '{{ dc_address }}'

  - name: Reinicia o Sistema
    win_reboot:
    when: res.reboot_required   
    delegate_to: '{{ dc_address }}'

  - name: Instala Active Directory
    win_feature: >
         name=AD-Domain-Services
         include_management_tools=yes
         include_sub_features=yes
         state=present
    register: result
    delegate_to: '{{ dc_address }}'

  - name: Cria o dominio
    win_domain: >
       dns_domain_name='{{ domain_name }}'
       safe_mode_password='{{ recovery_password }}'
    register: ad
    delegate_to: "{{ dc_address }}"

  - name: reinicia servidor
    win_reboot:
     msg: "Installing AD. Rebooting..."
     pre_reboot_delay: 15
    when: ad.changed
    delegate_to: "{{ dc_address }}"

  - name: Define DNS Interno
    win_dns_client:
      adapter_names: '*'
      ipv4_addresses:
      - '127.0.0.1'
    delegate_to: '{{ dc_address }}'

  - name: Cria reverse DNS zone
    win_shell: "Add-DnsServerPrimaryZone -NetworkID {{reverse_dns_zone}} -ReplicationScope Forest"
    delegate_to: "{{ dc_address }}"    
    retries: 30
    delay: 60
    register: result           
    until: result is succeeded

  - name: Instala IIS
    win_feature:
      name: "web-server"
      state: present
      restart: yes
      include_sub_features: yes
      include_management_tools: yes

  - name: Copia Certificado para o host
    win_copy:
      src: /home/guisousa/Adfs-Packer-Terraform/adfscert.pfx
      dest: C:\

  - name: Instala o Certificado 
    win_certificate_store:
      path: C:\adfscert.pfx
      state: present
      password: P@ssw0rd
      store_location: LocalMachine
      key_storage: machine
    become: yes
    become_method: runas
    become_user: SYSTEM

  - name: Instala ADFS
    win_feature: 
      name: ADFS-Federation
      state: present
      include_sub_features: true
      include_management_tools: true

  - name: Cria User
    win_domain_user:
      name: guisousa
      password: P@ssw0rd
      state: present
      groups:
       - Domain Admins

